google_news_queries:
  United States: 
    - "financial regulation"
    - "SEC rule"
    - "bank supervision"
    - "market conduct"
    - "ESG"
    - "sustainability"
    - "green finance"
    - "climate disclosure"
  United Kingdom: 
    - "FCA regulation"
    - "PRA rule"
    - "BoE policy"
    - "market abuse"
    - "listing rules"
    - "ESG"
    - "sustainability"
    - "green finance"
  European Union: 
    - "ESMA guideline"
    - "EBA rule"
    - "ECB policy"
    - "MiCA"
    - "ESG"
    - "sustainability"
    - "taxonomy"
    - "CSRD"
    - "SFDR"
  Norway: 
    - "Finanstilsynet regulation"
    - "financial supervision"
    - "bank compliance"
    - "ESG"
    - "sustainability"
    - "green finance"
  Japan: 
    - "JFSA regulation"
    - "financial supervision"
    - "crypto regulation"
    - "ESG"
    - "sustainability"
    - "green finance"
    - "site:fsa.go.jp"
    - "site:env.go.jp"
    - "金融庁 規制"             
    - "金融監督"  

direct_rss:
  United States:
    - "https://www.sec.gov/news/pressreleases.rss"
    - "https://www.federalreserve.gov/feeds/press_all.xml"
  United Kingdom:
    - "https://www.fca.org.uk/news/rss.xml"
    - "https://www.bankofengland.co.uk/rss/news"         
  European Union:
    - "https://www.eba.europa.eu/rss.xml"            
    - "https://www.ecb.europa.eu/rss/press.html"        
    - "https://www.ecb.europa.eu/rss/blog.html"         
    - "https://www.ecb.europa.eu/rss/statpress.html"      
  Norway:
    - "https://www.finanstilsynet.no/rss/nyheter/"            
    - "https://www.regjeringen.no/en/whatsnew/rss/id2006120/"  
  Japan: 
    - "https://www.fsa.go.jp/fsaEnNewsList_rss2.xml"

                        
